.intel_syntax noprefix
.text
.global nop_asm

nop_asm:

nop
nop
nop
nop
nop

nop
nop
nop
nop
nop

nop
nop
nop
nop
nop

nop
nop
nop
nop
nop

nop
nop
nop
nop
nop

nop
nop
nop
nop
nop

nop
nop
nop
nop
nop

nop
nop
nop
nop
nop

nop
nop
nop
nop
nop

nop
nop
nop
nop
nop

nop
nop
nop
nop
nop

nop
nop
nop
nop
nop

nop
nop
nop
nop
nop

nop
nop
nop
nop
nop

nop
nop
nop
nop
nop

nop
nop
nop
nop
nop

nop
nop
nop
nop
nop

nop
nop
nop
nop
nop

nop
nop
nop
nop
nop

nop
nop
nop
nop
nop
ret